[package]
name = "gpu-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.11.5"
cust = { version = "0.3.1", features = ["nvrtc"] }
thiserror = "2.0.3"
